name: Cache & Artifacts

on: [workflow_dispatch]

jobs:
    cache-and-artifacts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Cache node modules
              id: npm-cache
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: "npm-cache-${{hashFiles('**/package-lock.json')}}"
                restore-keys: | 
                    ${{runner.os}}-npm-cache-
                    ${{runner.os}}-npm
            
            - name: Display Cache
              run: echo '${{toJson(steps.npm-cache.outputs)}}'
            
            - name: Install dependencies
              run: npm install

            - name: Run Tests
              run: npm test

            - name: Upload Code Coverage Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: code-coverage
                path: coverage
                retention-days: 10

            - name: Use Axios
              uses: actions/github-script@v6
              with:
                script: |
                    const axios = require("axios");

                    const res = await axios("https://icanhazdadjoke.com/", {
                        headers: {
                            Accept: 'text/plain'
                        }
                    })

                    console.log(res.data)
