name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Ali"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: playpen-courses/workflows/.github/workflows/reusable-workflow.yml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access_token: ${{ secrets.ACCESS_SECRETS }}