name: Docker Run

on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: node:20.3-alpine3.17
            # credentials:
            #     username:
            #     password:
            env:
                URL: example.com
            # volumes:
            #     - volume_name:paths/in/container
            ports:
                - 80
        steps:
            - uses: actions/checkout@v4
            - name: List the dir
              run: ls -a
            - uses: actions/cache@v4
              with:
                key: docker
                path: /bin/tar
            - name: Log Container Details
              run: |-
                node -v
                cat /etc/os-release
            - name: Log Env Var
              run: echo $URL

            - name: Container in a Step
              uses: docker://node:18.16-alpine3.17
              with:
                args: -p 2+3
            
            - name: Container in a Step
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
