name: Dynamic Matrix

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating Systems
        type: string
        required: true
      node-version:
        description: Node Version
        type: string
        required: true



jobs:
    prepare-matrix:
      runs-on: ubuntu-latest
      steps:
        - name: Set up OS outputs
          id: os-split
          run: echo "step-output=value" >> $GITHUB_OUTPUT

        - name: Set up node-version outputs
          id: node-version-split
          run: echo "step-output=value 2" >> $GITHUB_OUTPUT

        - name: Use Output
          run: |-
            echo '${{steps.os-split.outputs.step-output}}'
            echo '${{steps.node-version-split.outputs.step-output}}'
    node-matrix:
        strategy:
            matrix:
                node-version: [14, 15, 16]
                os: ["ubuntu-latest", "windows-latest"]
        runs-on: ${{ matrix.os }}
        steps:
            - run: node -v
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v
            - name: Log all matrix
              run: echo '${{ toJson(matrix) }}'