name: Pull Request Auto Comments

on:
    pull_request_target:
        types: [opened]

jobs: 
    pr-auto-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Comment on a New PR
              uses: actions/github-script@v6
              with:
                script: |-
                    octokit.rest.issues.createComment({
                        owner: github.repository_owner,
                        repo: github.repository,
                        issue_number: context.issue.number,
                        body: "Thanks for contributing!",
                    });