name: Workflow Run Even

on:
    workflow_run:
        workflows: [Workflow Commands]
        types: [completed]
        branches:
            - main # means after completing Workflow Commands run in the main branch, trigger this workflow

jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I was triggered by other workflow"